### ISSUE TITLE
No content in downloaded file

### ISSUE THREAD

**Issue by summupv** [pegasystems/pega-logviewer#1]
I tried downloading the Pega logviewer tool, but it does not have any executable file except the READ ME file. Appreciate if you can look into the issue.

**Comment by Dgiffone** [comment]
You can download it from [releases page](https://github.com/pegasystems/pega-logviewer/releases) that is reachable from project home page. Scroll to the end where are download links

**Comment by vargm** [comment]
Udated the project page with a link to Releases page.
