### ISSUE TITLE
Can't run PEGA Log Viewer

### ISSUE THREAD

**Issue by Junicavi** [pegasystems/pega-logviewer#12]
I've been trying to run the app, but when I run the batch, the windows command pops up, but nothing happens, I've Java 8 installed, and the JAVA_HOME variable set up on my Windows 11 Environmen settings

**Comment by vargm** [comment]
Hi @Junicavi,
from windows, open the command prompt.
cd to the "<logviewer folder>\bin" folder. 
then execute the batch file ".\pega-logviewer.bat".
check what error is displayed on the command prompt.

Also check the "logs" folder for logs and errors.

**Comment by Junicavi** [comment]
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap

That's the error

**Comment by vargm** [comment]
it looks like you dont have enough ram on the system. by default the tool uses max 2G heap. 
you can update the heap settings in "pega-logviewer.bat" file. 
in the DEFAULT_JVM_OPTS look for options "-Xms1G" "-Xmx2G". 
if you want to reduce it you could set -Xmx to 1G, 
But this will cause out of memory errors when you load a bigger log files or more number of log file at the same time.

**Comment by Junicavi** [comment]
I've 16Gb, I don't think that's the problem

**Comment by vargm** [comment]
May be your current memory usage is high and there may not be enough free memory to allocate further 2GB.

**Comment by Junicavi** [comment]
It's is not

**Comment by Junicavi** [comment]
![image](https://user-images.githubusercontent.com/30063203/212898209-24a0fe24-8406-4f38-8b01-884ead87d87f.png)

**Comment by Junicavi** [comment]
As you see in the image, there almost 8Gb and the error remains the same

**Comment by vargm** [comment]
Can you also check if your java is 64bit?, 
check this by running "java -version" command on the command prompt
