### ISSUE TITLE
unable to run the pega-logviewer

### ISSUE THREAD

**Issue by ankit88guptastar** [pegasystems/pega-logviewer#5]
Hi team,
every time i run the pega-logviewer-3..cmd script, system displays the following error:

**Windows cannot find 'java'. Make sure you typed the name correctly, and then try again.**

could you please help.

**Comment by vargm** [comment]
Hi
This tool need Java 8 for execution. Please check 
1. if you have Java 8 installed.
2. the Java executable path is set in the "Path" environment variable, for ex "C:\Program Files\Java\jdk1.8.0_131\bin" or %JAVA_HOME%\bin.
3. run 'java -version' on a Windows command prompt to confirm that java can be run and the version is expected.

**Comment by biligeny** [comment]
will this work with OpenJDK9 later on?
